version: "3"
services:
  mongodb-dev:
    image: mongodb/mongodb-community-server:latest
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=mongo
      - MONGODB_INITDB_ROOT_PASSWORD=password
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    ports:
      - "27017:27017"
    networks:
      - mongodb-network
  mongo-express-dev:
    image: mongo-express:latest
    depends_on:
      - mongodb-dev
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb-dev
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    ports:
      - "8004:8081"
    networks:
      - mongodb-network
networks:
  mongodb-network:
    driver: bridge